PATH_NILSA = 'Sockets/Nilsa/'
PATH_WEB_DRIVER = 'Sockets/Browser/'
PATH_ATTACHMENTS_AVATARS = 'Attachments/Avatars/'
PATH_DOWNLOAD = 'c:/Users/Sanek/Downloads/'
FILE_FLAG = 'FLAG'
FILE_DATA = 'data'
API_GPT ='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'
TINDER = ['TinderSeleniumAuthorization']
WHATSAPP = [
   'WHATSAPP_SELENIUM_AUTHORIZATION',
   'WHATSAPP_SELENIUM_SEND_MESSAGE',
   'WHATSAPP_SELENIUM_SEND_MESSAGE_GPT',
   'WHATSAPP_SELENIUM_NEW_MESSAGES',
   'WHATSAPP_SELENIUM_CONTACTER_MESSAGE',
   'WHATSAPP_SELENIUM_UNREAD_CONTACTER_MESSAGES',
   'WHATSAPP_SELENIUM_GET_PHOTO_PERSONE',
   'WHATSAPP_SELENIUM_GET_PHOTO_CONTACTER',
   'WHATSAPP_SELENIUM_GET_FIRST_NAME_PERSONE',
   'WHATSAPP_SELENIUM_GET_LAST_NAME_PERSONE',
   'WHATSAPP_SELENIUM_GET_FIRST_NAME_CONTACTER',
   'WHATSAPP_SELENIUM_GET_LAST_NAME_CONTACTER',
]
TELEGRAM = [
   'TELEGRAM_SELENIUM_AUTHORIZATION',
   'TELEGRAM_SELENIUM_SEND_MESSAGE',
   'TELEGRAM_SELENIUM_SEND_MESSAGE_GPT',
   'TELEGRAM_SELENIUM_NEW_MESSAGES',
   'TELEGRAM_SELENIUM_CONTACTER_MESSAGE',
   'TELEGRAM_SELENIUM_GET_PHOTO_PERSONE',
   'TELEGRAM_SELENIUM_GET_FIRST_NAME_PERSONE',
   'TELEGRAM_SELENIUM_GET_LAST_NAME_PERSONE',
   'TELEGRAM_SELENIUM_GET_PHONE_PERSONE',
   'TELEGRAM_SELENIUM_GET_PEER_ID_PERSONE',
   'TELEGRAM_SELENIUM_GET_USERNAME_PERSONE',
   'TELEGRAM_SELENIUM_GET_INFO_PERSONE',
   'TELEGRAM_SELENIUM_GET_LINK_PERSONE',
   'TELEGRAM_SELENIUM_GET_PHOTO_CONTACTER',
   'TELEGRAM_SELENIUM_GET_FIRST_NAME_CONTACTER',
   'TELEGRAM_SELENIUM_GET_LAST_NAME_CONTACTER',
   'TELEGRAM_SELENIUM_GET_PHONE_CONTACTER',
   'TELEGRAM_SELENIUM_GET_PEER_ID_CONTACTER',
   'TELEGRAM_SELENIUM_GET_USERNAME_CONTACTER',
   'TELEGRAM_SELENIUM_GET_INFO_CONTACTER',
   'TELEGRAM_SELENIUM_GET_LINK_CONTACTER',
]